const LOGIN_CLIENT_TITLE = 'Ingreso tu documento';
const LOGIN_CLIENT_INPUT_IDENTIFIER_NUMBER = 'Número de identificación';

const REGISTER_CLIENT_INPUT_DOCUMENT = 'Documento de identificación';
const REGISTER_CLIENT_INPUT_NAME = 'Nombre';
const REGISTER_CLIENT_INPUT_LASTNAME = 'Apellido';
const REGISTER_CLIENT_INPUT_USERNAME = 'Usuario';
const REGISTER_CLIENT_INPUT_ADDRESS = 'Dirección';
const REGISTER_CLIENT_INPUT_EMAIL = 'Correo';
const REGISTER_CLIENT_INPUT_PHONE = 'Teléfono';
const REGISTER_CLIENT_SUBMIT = 'CONTINUAR';

const RECOVERY_CLIENT_PASSWORD = 'Recuperar contraseña';
const RECOVERY_CLIENT_INPUT_PASSWORD_CONFIRMATION = 'Confirma tu contraseña';
const RECOVERY_CLIENT_INPUT_PASSWORD = 'Contraseña';
const RECOVERY_CLIENT_SUBMIT = 'RECUPERAR';
const RECOVERY_CLIENT_INPUT_EMAIL = 'Correo';
const RECOVERY_CLIENT_NOT_FOUND_TOKEN = 'Debes ingresar por el link que te enviaron al correo, si no te llegó da click en el siguiente botón para recuperar contraseña';

const FORGOT_CLIENT_TITLE = 'Ingresa tu correo';
const FORGOT_CLIENT_INPUT_EMAIL = 'Correo';
const FORGOT_CLIENT_SUBMIT = 'ENVIAR CORREO';



//USER TERMINALS
const LOGIN_USER_TITLE = 'Ingresa tus datos';
const LOGIN_USER_INPUT_USERNAME = 'Username';
const LOGIN_USER_INPUT_PASSWORD = 'Contraseña';


const REGISTER_USER_INPUT_NAME = 'Nombre';
const REGISTER_USER_INPUT_USERNAME = 'Usuario';
const REGISTER_USER_INPUT_EMAIL = 'Correo';
const REGISTER_USER_PASSWORD = 'Contraseña';
const REGISTER_USER_PASSWORD_CONFIRMATION = 'Confirma la contraseña';
const REGISTER_USER_SUBMIT = 'CREAR';


export default {
    LOGIN_CLIENT_TITLE,
    LOGIN_CLIENT_INPUT_IDENTIFIER_NUMBER,
    REGISTER_CLIENT_INPUT_DOCUMENT,
    REGISTER_CLIENT_INPUT_NAME,
    REGISTER_CLIENT_INPUT_LASTNAME,
    REGISTER_CLIENT_INPUT_USERNAME,
    REGISTER_CLIENT_INPUT_ADDRESS,
    REGISTER_CLIENT_INPUT_EMAIL,
    REGISTER_CLIENT_INPUT_PHONE,
    RECOVERY_CLIENT_PASSWORD,
    RECOVERY_CLIENT_INPUT_PASSWORD_CONFIRMATION,
    RECOVERY_CLIENT_INPUT_PASSWORD,
    RECOVERY_CLIENT_SUBMIT,
    FORGOT_CLIENT_TITLE,
    FORGOT_CLIENT_INPUT_EMAIL,
    FORGOT_CLIENT_SUBMIT,
    RECOVERY_CLIENT_NOT_FOUND_TOKEN,
    RECOVERY_CLIENT_INPUT_EMAIL,
    REGISTER_CLIENT_SUBMIT,
    LOGIN_USER_INPUT_PASSWORD,
    LOGIN_USER_INPUT_USERNAME,
    LOGIN_USER_TITLE,
    REGISTER_USER_INPUT_NAME,
    REGISTER_USER_INPUT_USERNAME,
    REGISTER_USER_INPUT_EMAIL,
    REGISTER_USER_PASSWORD,
    REGISTER_USER_PASSWORD_CONFIRMATION,
    REGISTER_USER_SUBMIT
};
