const USER_INFO_TITLE = 'MIS DATOS';
const USER_INFO_CLIENT_INPUT_DOCUMENT = 'Documento de identificación';
const USER_INFO_CLIENT_INPUT_NAME = 'Nombre';
const USER_INFO_CLIENT_INPUT_LASTNAME = 'Apellido';
const USER_INFO_CLIENT_INPUT_USERNAME = 'Usuario';
const USER_INFO_CLIENT_INPUT_ADDRESS = 'Dirección';
const USER_INFO_CLIENT_INPUT_PHONE = 'Teléfono';
const USER_INFO_CLIENT_SUBMIT = 'GUARDAR';


export default {
    USER_INFO_TITLE,
    USER_INFO_CLIENT_INPUT_DOCUMENT,
    USER_INFO_CLIENT_INPUT_NAME,
    USER_INFO_CLIENT_INPUT_LASTNAME,
    USER_INFO_CLIENT_INPUT_USERNAME,
    USER_INFO_CLIENT_INPUT_ADDRESS,
    USER_INFO_CLIENT_INPUT_PHONE,
    USER_INFO_CLIENT_SUBMIT
};
